import type { Metadata } from "next";
import "@/styles/loginpage.css";
import "./globals.css";
import "../../styles/index.scss";


export const metadata: Metadata = {
  title: "PSM GOLD CRAFT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        {children}
      </body>
    </html>
  );
}